### Cadastrar um aluno
POST http://localhost:5022/aluno/cadastrar
Content-Type: application/json

{
    "nome": "Maria",
    "sobrenome": "Almeida"
}

##ENDPOIT IMC
###Cadastrar um Imc
POST http://localhost:5022/cadastrar/imcs
Content-Type: application/json

{
    "peso": 70,
    "altura": 1.75,
    "alunoId": 1  
}
###Listar Imc
GET http://localhost:5022/listar/imcs/1

PUT http://localhost:5022/imc/alterar/1
Content-Type: application/json
{
    "peso": 75,
    "altura": 1.80
}

GET http://localhost:5022/listar/imcs

