### Cadastrar um aluno
POST http://localhost:5022/aluno/cadastrar
Content-Type: application/json

{
    "nome": "Maria",
    "sobrenome": "Almeida"
}

##ENDPOIT IMC

###Cadastrar um Imc
POST http://localhost:5022/cadastrar/imc
Content-Type: application/json

{
    "nome" : "nike",
    "altura" : 2,
    "preco" : 200.25,
    "categoriaId" : 1
}